# Generated by Django 5.2.7 on 2025-11-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorprofile',
            old_name='year_semester',
            new_name='year',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='mentor_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
