# Generated by Django 5.2.7 on 2025-11-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_rename_year_semester_mentorprofile_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='division_batch',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='year',
            field=models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year')], max_length=20, null=True),
        ),
    ]
