# Generated by Django 5.2.7 on 2025-11-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='semester1_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester2_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester3_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester4_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester5_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester6_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
    ]
